version: '2'
services:
    sslocalA:
        image: mritd/shadowsocks
        command: [ "-m","ss-local","-s","-c /etc/shadowsocks-libev/config.json" ]
        volumes:
            - '/var/lib/overfw/etc/shadowsocks/hkjqk.json:/etc/shadowsocks-libev/config.json:ro'

    sslocalB:
        image: mritd/shadowsocks
        command: [ "-m","ss-local","-s","-c /etc/shadowsocks-libev/config.json" ]
        volumes:
            - '/var/lib/overfw/etc/shadowsocks/us1.json:/etc/shadowsocks-libev/config.json:ro'

    haproxy:
        image: haproxy
        links:
            - sslocalA
            - sslocalB
        ports:
            - '7070:2222/tcp'
            - '1111:1111/tcp'
        volumes:
            - '/var/lib/overfw/etc/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro'
