global:
    scrape_interval: 5s

scrape_configs:
  - job_name: 'company1'
    static_configs:
      - targets:
          - 10.0.0.2  # SNMP device(switch etc.).
    metrics_path: /snmp
    params:
      module: [company1]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9116  # The SNMP exporter's real hostname:port.
  - job_name: 'company2'
    static_configs:
      - targets:
        - 10.0.0.3  # SNMP device.
    metrics_path: /snmp
    params:
      module: [company2]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9116  # The SNMP exporter's real hostname:port.
